eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance: 
   hostname: localhost
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2




microservice:
 payment-service:
  enpoints: 
   endpoint: 
    uri : http://PAYMENT-SERVICE/payment/doPayment
 order-service:
  enpoints: 
   endpoint: 
    uri : http://ORDER-SERVICE/order/bookOrder
